name: pr

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    tags:
      - v*
    branches:
      - main
      - development
  pull_request:

jobs:
  checks:
    name: pull request checks
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.29

      - name: run tests
        run: go test .

      - name: compile the project
        run: go build