---
name: run-go-slack-weather

on:
  push:
    branches:
      - main
  schedule:
      - cron: '*/30 * * * *'

jobs:
  run-go-slack-weather:
    runs-on: ubuntu-latest
    name: build and run
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3.4.0
        with:
          go-version: '1.16'

      - name: run-go-slack-weather
        run: go run main.go
        env:
          CITY: ${{ secrets.CITY }}
          MESSAGE: ${{ secrets.MESSAGE }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          WEATHER_API: ${{ secrets.WEATHER_API }}
