---
name: run-go-release

on:
  create:
    tags:
      - v*

jobs:
  run-go-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: run-go-release
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
