on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

name: go-slack-weather

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and run
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go run cmd/main.go
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CITY: ${{ secrets.CITY }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          WEATHER_API: ${{ secrets.WEATHER_API }}